version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=commerce
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=test
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/commerce?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin